"Plugins
set nocompatible              " be iMproved, required
filetype off                  " required
"filetype on
"set rtp+=~/.vim/plugged/vim-plug/plug.vim
call plug#begin('~/.vim/plugged')

Plug 'junegunn/vim-plug'
Plug 'Valloric/YouCompleteMe'
Plug 'luochen1990/rainbow' "括号彩色配对
Plug 'jiangmiao/auto-pairs'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'notpratheek/vim-luna'   "luna theme
Plug 'mbbill/undotree'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter' "快速注释
Plug 'Yggdroot/indentLine'    "缩进提示
Plug 'ctrlpvim/ctrlp.vim'
Plug 'ntpeters/vim-better-whitespace'
Plug 'addisonbean/vim-xcode-theme'
Plug 'sickill/vim-monokai'
"Plug 'fatih/vim-go'
Plug 'Chiel92/vim-autoformat'
Plug 'christoomey/vim-tmux-navigator'
Plug 'tpope/vim-obsession'
"Plug 'tomasr/molokai' "molokai theme
"Plug 'Raimondi/delimitMate' "括号自动补全
"Plug 'altercation/vim-colors-solarized'   "solarized theme
"Plug 'jeaye/color_coded'  "代码彩色
"Plug 'majutsushi/tagbar'
"Plug 'rdnetto/YCM-Generator'
"Plug 'lfilho/cosco.vim'
"Plug 'taglist.vim'
" All of your Plugs must be added before the following line

call plug#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
filetype plugin on

" ------Basic Configurations------
let mapleader = ','

syntax on "语法高亮
syntax enable
set autoread "Auto read when a file is changed from the outside

"command :W to wirte the file with sudo
command W w !sudo tee % > /dev/null

set number  "显示行号
set so=7 "Set 7 lines to the cursor, when moving vertically using j/k
set ruler "Always show current position
set laststatus=2 "show status line with the specific height

set autoindent
set smartindent "indentation style
"set cindent
set cino=g0 "缩进设置 class 内部的private,protect,public,缩进0
"set autoindent
set backspace=indent,eol,start
set expandtab   "加入的缩进用空格代替
set tabstop=4   "读取的缩进用4空格代替
set softtabstop=4   "退格时4个空格当作一个缩进删除
set shiftwidth=4    "缩进宽度4空格
set showtabline=1
set textwidth=100
set colorcolumn=+1
hi ColorColumn ctermbg=red
hi ColorColumn guibg=red
"set foldcolumn=1 " Add a bit extra margin to the left

set incsearch "单词内部搜索
set ignorecase "Ignore case when searching
set smartcase  "搜索小写字母忽略大小写，大写字母不忽略
set hlsearch "高亮查找结果
set magic "For reugular expression turn magic on( need \ before meta characters only expect * . $ ^ )

set fileformat=unix
set t_Co=256
set background=light
colorscheme luna-term
set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1
set enc=utf-8
"set t_ti=t_te= "退出vim后仍显示在终端
"set ffs=unix,dos,mac "Default use unix End-Of-Line style LF
"set fileencoding=utf-8
"set nobackup

set wildmenu " Turn on the Wild menu
" Ignore compiled files
set wildignore=*.o,*~,*.pyc
if has("win16") || has("win32")
    set wildignore+=.git\*,.hg\*,.svn\*
else
    set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*/.DS_Store
endif

" Super useful! From an idea by Michael Naumann. Search the word under the curser use * or # in visual mode
vnoremap <silent> * :<C-u>call VisualSelection('', '')<CR>/<C-R>=@/<CR><CR>
vnoremap <silent> # :<C-u>call VisualSelection('', '')<CR>?<C-R>=@/<CR><CR>

nnoremap <leader>te :tabnew<CR>
nnoremap <leader>tn :tabn<CR>
nnoremap <leader>tp :tabp<CR>
nnoremap <leader>tc :tabc<CR>
nnoremap <leader>to :tabonly<CR>
nnoremap <leader>bn :bn<CR>
nnoremap <leader>bp :bp<CR>
nnoremap <A-Right> :vertical res +1<CR>
nnoremap <A-Left> :vertical res -1<CR>
nnoremap <A-Up> :res -1<CR>
nnoremap <A-Down> :res +1<CR>
nnoremap <leader>bd :Bclose<cr>:tabclose<cr>gT
nnoremap <silent> <leader><CR> :noh<CR>

"insert mode下Shift-Enter直接下一行
inoremap <S-CR> <ESC>o
"insert mode下Ctrl-H = Backspace
inoremap <C-H> <BS>

"输入{} 自动换行
inoremap <expr> <cr> getline(".")[col(".")-2:col(".")-1]=="{}" ? "<cr><esc>O" : "<cr>"

"Return to last eidt position when opening files
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Don't close window, when deleting a buffer
command! Bclose call <SID>BufcloseCloseIt()
function! <SID>BufcloseCloseIt()
    let l:currentBufNum = bufnr("%")
    let l:alternateBufNum = bufnr("#")

    if buflisted(l:alternateBufNum)
        buffer #
    else
        bnext
    endif

    if bufnr("%") == l:currentBufNum
        new
    endif

    if buflisted(l:currentBufNum)
        execute("bdelete! ".l:currentBufNum)
    endif
endfunction

function! VisualSelection(direction, extra_filter) range
    let l:saved_reg = @"
    execute "normal! vgvy"

    let l:pattern = escape(@", "\\/.*'$^~[]")
    let l:pattern = substitute(l:pattern, "\n$", "", "")

    if a:direction == 'gv'
        call CmdLine("Ack '" . l:pattern . "' " )
    elseif a:direction == 'replace'
        call CmdLine("%s" . '/'. l:pattern . '/')
    endif

    let @/ = l:pattern
    let @" = l:saved_reg
endfunction


" --------------Plugin Configurations--------------
"彩色括号配对配置
let g:rainbow_active=1
let g:rainbow_conf = {
            \   'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick'],
            \   'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta'],
            \   'operators': '_,_',
            \   'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
            \   'separately': {
            \       '*': {},
            \       'tex': {
            \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/'],
            \       },
            \       'lisp': {
            \           'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
            \       },
            \       'vim': {
            \           'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody'],
            \       },
            \       'html': {
            \           'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
            \       },
            \       'css': 0,
            \   }
            \}

"youcompleteme Ycm
nnoremap <F5> :YcmForceCompileAndDiagnostics<CR>
let g:ycm_min_num_of_chars_for_completion = 3 "至少3个字符启动补全，标识符补全，不是语义补全
let g:ycm_min_num_identifier_candidate_chars = 3 "标识符补全候选项中至少显示3个字符

let g:ycm_complete_in_comments = 1 "注释时也启用补全
let g:ycm_complete_in_strings = 1 "字符串内也启用补全
"收集tag内的符号，ctags 需要使用 --fields=+l 选项, 默认关闭该选项
let g:ycm_collect_identifiers_from_tags_files = 0
"ycmd server 采用的Python解释器,设置为安装install.py的解释器
let g:ycm_server_python_interpreter = 'python3'
"结合ycm_extra_conf.py,以下两个选项可以动态地控制Python补全相对的解释器和文件路径
let g:ycm_python_interpreter_path = ''
let g:ycm_python_sys_path = []
let g:ycm_extra_conf_vim_data = [
            \ 'g:ycm_python_interpreter_path',
            \ 'g:ycm_python_sys_path'
            \]

"不显示预览窗口
set completeopt-=preview
let g:ycm_add_preview_to_completeopt = 0
"用户选择提供的候选补全项，自动关闭预览窗口
let g:ycm_autoclose_preview_window_after_completion = 1
"离开插入模式后，自动关闭预览窗口
let g:ycm_autoclose_preview_window_after_insertion = 0
"显示的最大诊断数量
let g:ycm_max_diagnostics_to_display = 30
"选择候选补全项的键
let g:ycm_key_list_select_completion = ['<TAB>','<Down>']
let g:ycm_key_list_previous_completion = ['<S-TAB>','<UP>']
let g:ycm_key_list_stop_completion = ['<C-y>']
"调用语义补全的选项
let g:ycm_key_invoke_completion = '<C-Space>'
"光标在出错行时，显示详细错误内容
let g:ycm_key_detailed_diagnostics = '<leader>d'
".ycm_extra_conf.py 全局路径
let g:ycm_global_ycm_extra_conf = '~/.vim/ycm_extra_conf.py'
"载入.ycm_extra_conf.py前进行确认
"let g:ycm_extra_conf_globallist = ['~/.vim/ycm_extra_conf.py']
"跳转到定义或声明
nnoremap <leader>jd :YcmCompleter GoTo<CR>
nnoremap <leader>jdc :YcmCompleter GoToDeclaration<CR>
"从tags中收集补全 可能会影响速度
" ctags 需要 调用加上 --fields=+l
" exuberant ctags format 默认对.h采用c++ 标签
" 对于 c 工程  ctags 调用 --langmap=c:.c.h
let g:ycm_collect_identifiers_from_tags_files=1

"vim-airline
"let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme ='luna'

"indentLine
let g:indentLine_setColors = 0
let g:indentLine_enabled = 1
"let g:indentLine_fileType = []
"let g:indentLine_fileTypeExclude = []

""color_coded
"let g:color_coded_enabled = 1
"let g:color_coded_filetypes = ['c', 'cpp']

"undotree
nnoremap <leader>ud :UndotreeToggle<CR>
let g:undotree_WindowLayout = 2

"NERDtree
nnoremap <leader>nt :NERDTree<CR>
let NERDTreeWinPos='right'

"CtrlP
let g:ctrlp_map = '<C-p>'
let g:ctrlp_cmd = 'CtrlPBuffer'
let g:ctrlp_working_path_mode = 'wa' "未指定查找开始目录时的起始模式
let g:ctrlp_switch_buffer='Et' "当打开一个已经打开的文件时跳转过去而不是重新打开一个窗口
let g:ctrlp_tabpage_position = 'ac' "在当前标签的后面打开新标签项
"设设置ctrlp按键, CR为在新标签内打开, 双击左键为在当前标签打开
let g:ctrlp_prompt_mappings = {
            \ 'AcceptSelection("e")': ['<2-LeftMouse>'],
            \ 'AcceptSelection("t")': ['<cr>'],
            \ }

""delimitMate
"let delimitMate_autoclose = 0
"au FileType cpp,python,go let b:delimitMate_autoclose = 1

"vim-better-whitespace
nnoremap <leader>s :StripWhitespace<CR>

"tagbar
"nnoremap <F8> :TagbarToggle<CR>

"vim-autoformat
let g:formatterpath = [] "formatter路径, 在PATH中时不需要添加
let g:autoformat_verbosemode = 1
let g:formatdef_goimports = '"goimports"'
let g:formatdef_gofmt = '"gofmt"'
let g:formatters_go = ['goimports', 'gofmt']
"let g:autoformat_autoindent = 0 "文件类型没有formatter时, 进行缩进,tab修改,删除trailing三种基本操作
"let g:autoformat_retab = 0
"let g:autoformat_remove_trailing_spaces = 0

"vim-go
let g:go_fmt_command = "goimports"

"ctags
"CTRL-] 跳转到定义处
"CTRL-T 跳回来
"nnoremap <leader>cg :!ctags -R --c++-kinds=+p --fields=+liaS --extra=+q --language-force=C++

"cscope
"nnoremap <leader>co :!cscope_gen.sh
"cscope 查找之后利用 :cw 查看
"set cscopequickfix=s-,c-,d-,i-,t-,e-
""cscope -Rbkq
""cscope command
"":cs find {querytype} {name}
""{querytype} 即相对应于实际的cscope行接口数字，同时也相对应于nvi命令：
"0或者s   ―― 查找这个C符号
"1或者g  ―― 查找这个定义
"2或者d  ―― 查找被这个函数调用的函数（们）
"3或者c  ―― 查找调用这个函数的函数（们）
"4或者t   ―― 查找这个字符串
"6或者e  ―― 查找这个egrep匹配模式
"7或者f   ―― 查找这个文件
"8或者i   ―― 查找#include这个文件的文件（们）
"if has("cscope")
"set csprg=/usr/bin/cscope
"set csto=1
"set cst
"set nocsverb
"if filereadable("cscope.out")
"cscope add cscope.out
"endif
"set csverb
"endif
"cscope 快捷键
"nmap <C-_>s :cs find s <C-R>=expand("<cword>")<CR><CR>
"nmap <C-_>g :cs find g <C-R>=expand("<cword>")<CR><CR>
"nmap <C-_>c :cs find c <C-R>=expand("<cword>")<CR><CR>
"nmap <C-_>t :cs find t <C-R>=expand("<cword>")<CR><CR>
"nmap <C-_>e :cs find e <C-R>=expand("<cword>")<CR><CR>
"nmap <C-_>f :cs find f <C-R>=expand("<cfile>")<CR><CR>
"nmap <C-_>i :cs find i ^<C-R>=expand("<cfile>")<CR>$<CR>
"nmap <C-_>d :cs find d <C-R>=expand("<cword>")<CR><CR>"

